In [ ]:
import quopri, html, re
from bs4 import BeautifulSoup

def clean_html(s):
    if s is None:
        return ""
    # decode quoted-printable if present
    try:
        s = quopri.decodestring(s).decode("utf-8", errors="replace")
    except Exception:
        pass
    # unescape HTML entities
    s = html.unescape(s)
    # remove HTML tags using BS4
    s = BeautifulSoup(s, "html.parser").get_text(" ", strip=True)
    # collapse whitespace/newlines
    return " ".join(s.split())

# apply to dataframe column
df["clean_text"] = df["text"].apply(clean_html)

# preview
print(df[["subject","clean_text"]].head(5))

In [137]:
import numpy as np 
import pandas as pd
df1 = pd.read_csv("/run/media/darshchouhan/New Volume/DL-Algorithm/hyperparameters/spam.csv")
df2 = pd.read_csv("/run/media/darshchouhan/New Volume/DL-Algorithm/hyperparameters/ham.csv")

In [138]:
df1.shape

(496, 3)

In [139]:
df1

     Unnamed: 0                                               text  label
0             0  Save up to 70% on Life Insurance. Why Spend Mo...      0
1             1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      0
2             2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      0
3             3  ##############################################...      0
4             4  I thought you might like these:\n1) Slim Down ...      0
..          ...                                                ...    ...
491         491  Let \n        Mortgage Lenders compete for you...      0
492         492  THANK YOU FOR SHOPPING WITH US GIFTS FOR ALL O...      0
493         493  The \n            Famous eBay Marketing e-Cour...      0
494         494  (Hello,This is Chinese Traditional) ë×Óà]¼þ ¡...      0
495         495  social\n\n\n\nOn January 1st 2002, the Europea...      0

[496 rows x 3 columns]

In [140]:
df2

      Unnamed: 0                                               text  label
0              0  > From: fork-admin@xent.com [mailto:fork-admin...      0
1              1  Hi,\n\nOn Sun, 01 Sep 2002 00:05:03 MDT Reg Cl...      0
2              2  On Fri Sep 13 2002 at 02:03, Robert Elz wrote:...      0
3              3  On Thu, 2002-08-29 at 01:06, Matthias Saou wro...      0
4              4  Hi, I'm building an rpm for the resin webserve...      0
...          ...                                                ...    ...
2546        2546  >>>>> "E" == Eirikur Hallgrimsson writes:\n\n ...      0
2547        2547  On Monday, August 26, 2002, at 09:59  AM, Tom ...      0
2548        2548  bitbitch@magnesium.net wrote:\n > Well Beberg,...      0
2549        2549  Reza B'Far (eBuilt) wrote:\n> problems.... Why...      0
2550        2550  On Sun, 1 Sep 2002, Reza B'Far (eBuilt) wrote:...      0

[2551 rows x 3 columns]

In [141]:
df2.shape

(2551, 3)

In [142]:
df1['label']=1

In [143]:
df2['label']=0

In [144]:
df1

     Unnamed: 0                                               text  label
0             0  Save up to 70% on Life Insurance. Why Spend Mo...      1
1             1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2             2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3             3  ##############################################...      1
4             4  I thought you might like these:\n1) Slim Down ...      1
..          ...                                                ...    ...
491         491  Let \n        Mortgage Lenders compete for you...      1
492         492  THANK YOU FOR SHOPPING WITH US GIFTS FOR ALL O...      1
493         493  The \n            Famous eBay Marketing e-Cour...      1
494         494  (Hello,This is Chinese Traditional) ë×Óà]¼þ ¡...      1
495         495  social\n\n\n\nOn January 1st 2002, the Europea...      1

[496 rows x 3 columns]

In [145]:
df2

      Unnamed: 0                                               text  label
0              0  > From: fork-admin@xent.com [mailto:fork-admin...      0
1              1  Hi,\n\nOn Sun, 01 Sep 2002 00:05:03 MDT Reg Cl...      0
2              2  On Fri Sep 13 2002 at 02:03, Robert Elz wrote:...      0
3              3  On Thu, 2002-08-29 at 01:06, Matthias Saou wro...      0
4              4  Hi, I'm building an rpm for the resin webserve...      0
...          ...                                                ...    ...
2546        2546  >>>>> "E" == Eirikur Hallgrimsson writes:\n\n ...      0
2547        2547  On Monday, August 26, 2002, at 09:59  AM, Tom ...      0
2548        2548  bitbitch@magnesium.net wrote:\n > Well Beberg,...      0
2549        2549  Reza B'Far (eBuilt) wrote:\n> problems.... Why...      0
2550        2550  On Sun, 1 Sep 2002, Reza B'Far (eBuilt) wrote:...      0

[2551 rows x 3 columns]

In [146]:
new_data=pd.concat([df1,df2],axis=0)

In [147]:
new_data

      Unnamed: 0                                               text  label
0              0  Save up to 70% on Life Insurance. Why Spend Mo...      1
1              1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2              2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3              3  ##############################################...      1
4              4  I thought you might like these:\n1) Slim Down ...      1
...          ...                                                ...    ...
2546        2546  >>>>> "E" == Eirikur Hallgrimsson writes:\n\n ...      0
2547        2547  On Monday, August 26, 2002, at 09:59  AM, Tom ...      0
2548        2548  bitbitch@magnesium.net wrote:\n > Well Beberg,...      0
2549        2549  Reza B'Far (eBuilt) wrote:\n> problems.... Why...      0
2550        2550  On Sun, 1 Sep 2002, Reza B'Far (eBuilt) wrote:...      0

[3047 rows x 3 columns]

In [148]:
new_data['label'].value_counts()

label
0    2551
1     496
Name: count, dtype: int64

In [149]:
new_data['label']

0       1
1       1
2       1
3       1
4       1
       ..
2546    0
2547    0
2548    0
2549    0
2550    0
Name: label, Length: 3047, dtype: int64

In [150]:
new_data = new_data.sample(frac=1,random_state=42).reset_index(drop=True)

In [151]:
new_data

      Unnamed: 0                                               text  label
0           1086  > That always amazes me about 'regular' dreams...      0
1           1871  URL: http://www.newsisfree.com/click/-2,865571...      0
2           1595  URL: http://diveintomark.org/archives/2002/09/...      0
3            343  Opportunity is knocking. Why?\n\nBecause mortg...      1
4           2165  Hi all,\n\nWe're looking for an experienced IT...      0
...          ...                                                ...    ...
3042        1142  Update of /cvsroot/spamassassin/spamassassin\n...      0
3043         599  URL: http://www.newsisfree.com/click/-0,861366...      0
3044         634  Bill Stoddard wrote:\n\n>>No one likes commerc...      0
3045         798  Hi,\n\nJust the kind of announce I make once i...      0
3046         364  jm@jmason.org (Justin Mason) writes:\n\n>>>   ...      0

[3047 rows x 3 columns]

In [152]:
new_data['label'].value_counts()

label
0    2551
1     496
Name: count, dtype: int64

In [153]:
import re
def clean_html(text):
  clean= re.compile('<.*?>/')
  return re.sub(clean,'',text)

In [154]:
new_data['text']=new_data['text'].apply(clean_html)

In [155]:
new_data['label'].value_counts()

label
0    2551
1     496
Name: count, dtype: int64

In [156]:
import quopri, html, re
from bs4 import BeautifulSoup

def clean_html(s):
    if s is None:
        return ""
    # decode quoted-printable if present
    try:
        s = quopri.decodestring(s).decode("utf-8", errors="replace")
    except Exception:
        pass
    # unescape HTML entities
    s = html.unescape(s)
    # remove HTML tags using BS4
    s = BeautifulSoup(s, "html.parser").get_text(" ", strip=True)
    # collapse whitespace/newlines
    return " ".join(s.split())


# preview

In [157]:
new_data['label'].value_counts()

label
0    2551
1     496
Name: count, dtype: int64

In [158]:
def clean_text(text):
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', ' ', text)

    # Keep only alphabets
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [159]:
new_data['label'].value_counts()

label
0    2551
1     496
Name: count, dtype: int64

In [160]:
new_data['text'] = new_data['text'].apply(clean_text)

In [161]:
new_data

      Unnamed: 0                                               text  label
0           1086  that always amazes me about regular dreams how...      0
1           1871  url date t afghanistan in his final report one...      0
2           1595  url date t mark newhouse css design taming lis...      0
3            343  opportunity is knocking why because mortgage r...      1
4           2165  hi all we re looking for an experienced it sup...      0
...          ...                                                ...    ...
3042        1142  update of cvsroot spamassassin spamassassin in...      0
3043         599  url date t rendering polygons is not as easy a...      0
3044         634  bill stoddard wrote no one likes commercial sp...      0
3045         798  hi just the kind of announce i make once in a ...      0
3046         364  justin mason writes date in past spam phrase s...      0

[3047 rows x 3 columns]

In [162]:
def convert_lower(text):
  return  text.lower()

In [163]:
new_data['text']= new_data['text'].apply(convert_lower)

In [164]:
new_data

      Unnamed: 0                                               text  label
0           1086  that always amazes me about regular dreams how...      0
1           1871  url date t afghanistan in his final report one...      0
2           1595  url date t mark newhouse css design taming lis...      0
3            343  opportunity is knocking why because mortgage r...      1
4           2165  hi all we re looking for an experienced it sup...      0
...          ...                                                ...    ...
3042        1142  update of cvsroot spamassassin spamassassin in...      0
3043         599  url date t rendering polygons is not as easy a...      0
3044         634  bill stoddard wrote no one likes commercial sp...      0
3045         798  hi just the kind of announce i make once in a ...      0
3046         364  justin mason writes date in past spam phrase s...      0

[3047 rows x 3 columns]

In [165]:
new_data['label'].value_counts()

label
0    2551
1     496
Name: count, dtype: int64

In [166]:
def remove_special(text):
  x=''
  for i in text:
    if i.isalnum():
      x=x+i
    else:
      x=x+' '
  return x

In [167]:
new_data['text'] = new_data['text'].apply(remove_special)

In [168]:
new_data

      Unnamed: 0                                               text  label
0           1086  that always amazes me about regular dreams how...      0
1           1871  url date t afghanistan in his final report one...      0
2           1595  url date t mark newhouse css design taming lis...      0
3            343  opportunity is knocking why because mortgage r...      1
4           2165  hi all we re looking for an experienced it sup...      0
...          ...                                                ...    ...
3042        1142  update of cvsroot spamassassin spamassassin in...      0
3043         599  url date t rendering polygons is not as easy a...      0
3044         634  bill stoddard wrote no one likes commercial sp...      0
3045         798  hi just the kind of announce i make once in a ...      0
3046         364  justin mason writes date in past spam phrase s...      0

[3047 rows x 3 columns]

In [169]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

In [170]:
new_data['label'].value_counts()

label
0    2551
1     496
Name: count, dtype: int64

In [171]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))   # Create once

def remove_stopwords(text):
    words = [word for word in text.split() if word not in stop_words]
    return " ".join(words)

In [172]:
print(remove_stopwords('dancing'))

dancing

In [173]:
new_data['text']=new_data['text'].apply(remove_stopwords)

In [174]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

ps = PorterStemmer()

def stem_text(text):
    tokens = word_tokenize(text)
    return [ps.stem(word) for word in tokens]

In [175]:
new_data

      Unnamed: 0                                               text  label
0           1086  always amazes regular dreams often come true s...      0
1           1871  url date afghanistan final report one year beg...      0
2           1595  url date mark newhouse css design taming lists...      0
3            343  opportunity knocking mortgage rates rising nat...      1
4           2165  hi looking experienced support person school e...      0
...          ...                                                ...    ...
3042        1142  update cvsroot spamassassin spamassassin direc...      0
3043         599  url date rendering polygons easy used reason v...      0
3044         634  bill stoddard wrote one likes commercial spam ...      0
3045         798  hi kind announce make rebuilt new alsaplayer p...      0
3046         364  justin mason writes date past spam phrase spam...      0

[3047 rows x 3 columns]

In [176]:
new_data['label'].value_counts()

label
0    2551
1     496
Name: count, dtype: int64

In [177]:
tokens = new_data['text'].apply(stem_text)

In [178]:
new_data['tokens'] = tokens

In [179]:
new_data['label'].value_counts()

label
0    2551
1     496
Name: count, dtype: int64

### Now we will use the multimodel Binariser to convert to sparse matrix for the transformation

In [180]:
from sklearn.preprocessing import MultiLabelBinarizer
model = MultiLabelBinarizer()
word_matrix = model.fit_transform(new_data['tokens'])
word_matrix = pd.DataFrame(word_matrix,columns=model.classes_,index=new_data.index)

In [181]:
word_matrix.info()

<class 'pandas.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Columns: 30382 entries, a to zzzzx
dtypes: int64(30382)
memory usage: 706.3 MB

In [182]:
final_data=pd.concat([new_data,word_matrix],axis=1)

In [183]:
final_data = final_data.drop('text',axis=1)

In [184]:
final_data = final_data.drop('tokens',axis=1)

In [185]:
y = type(final_data['label'])
print(y)

<class 'pandas.DataFrame'>

In [186]:
y.shape

In [188]:
X = final_data.iloc[:,3:-1]
y = final_data['label']

In [189]:
y

      label  label
0         0      0
1         0      0
2         0      0
3         1      0
4         0      0
...     ...    ...
3042      0      0
3043      0      0
3044      0      0
3045      0      0
3046      0      0

[3047 rows x 2 columns]

In [190]:
y

      label  label
0         0      0
1         0      0
2         0      0
3         1      0
4         0      0
...     ...    ...
3042      0      0
3043      0      0
3044      0      0
3045      0      0
3046      0      0

[3047 rows x 2 columns]

In [191]:
X

      aa  aaa  aaaaaa  aaaaaaaaaa  ...  zzzzason  zzzzcc  zzzzotm  zzzzteana
0      0    0       0           0  ...         0       0        0          0
1      0    0       0           0  ...         0       0        0          0
2      0    0       0           0  ...         0       0        0          0
3      0    0       0           0  ...         0       0        0          0
4      0    0       0           0  ...         0       0        0          0
...   ..  ...     ...         ...  ...       ...     ...      ...        ...
3042   0    0       0           0  ...         0       0        0          0
3043   0    0       0           0  ...         0       0        0          0
3044   0    0       0           0  ...         0       0        0          0
3045   0    0       0           0  ...         0       0        0          0
3046   0    0       0           0  ...         0       0        0          0

[3047 rows x 30379 columns]

In [197]:
y = final_data.loc[:, 'label'].iloc[:, 0]

In [200]:
y.value_counts()

label
0    2551
1     496
Name: count, dtype: int64

In [201]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
X_train.shape

(2437, 30379)

In [202]:
from sklearn.feature_selection import SelectKBest, chi2

selector = SelectKBest(
    score_func=chi2,
    k=7000
)


X_train = selector.fit_transform(X_train, y_train)
X_test = selector.transform(X_test)

In [205]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
from sklearn.ensemble import RandomForestClassifier
model.fit(X_train,y_train)
model2 = RandomForestClassifier(class_weight='balanced')
model2.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced')

In [207]:
### Using Imbalance Sampling

In [208]:
from sklearn.metrics import accuracy_score
prediction = model.predict(X_test)
prediction2  = model2.predict(X_test)
print("BernoulliNB",accuracy_score(y_test,prediction))
print("RandomForest",accuracy_score(y_test,prediction2))

BernoulliNB 0.9163934426229509
RandomForest 0.9868852459016394

In [210]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train,
    y_train
)

#### Since the final Dataset had very less

In [214]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
from sklearn.ensemble import RandomForestClassifier
model.fit(X_train_resampled,y_train_resampled)
model2 = RandomForestClassifier()
model2.fit(X_train,y_train)

RandomForestClassifier()

In [215]:
from sklearn.metrics import accuracy_score
prediction = model.predict(X_test)
prediction2  = model2.predict(X_test)
print("BernoulliNB",accuracy_score(y_test,prediction))
print("RandomForest",accuracy_score(y_test,prediction2))

BernoulliNB 0.9967213114754099
RandomForest 0.9852459016393442